# services:
#   frontend:
#     build: frontend
#     ports:
#       - "5173:5173"
#     networks:
#       - d2

#   backend1:
#     build: backend
#     networks:
#       - d2
#     depends_on:
#       - mongo

#   backend2:
#     build: backend
#     networks:
#       - d2
#     depends_on:
#       - mongo

#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./certs:/etc/nginx/ssl:ro
#     depends_on:
#       - backend1
#       - backend2
#     networks:
#       - d2


#   mongo:
#     image: mongo:latest
#     ports:
#       - "27018:27017"
#     networks:
#       - d2

# networks:
#   d2:
#     driver: bridge


services:
  frontend:
    build: frontend
    networks:
      - d2

  backend1:
    build: backend
    networks:
      - d2
    depends_on:
      - mongo

  backend2:
    build: backend
    networks:
      - d2
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend1
      - backend2
    networks:
      - d2

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - d2

networks:
  d2:
    driver: bridge
